name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      run_only_non_integration_tests:
        description: 'Run only non-integration tests'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.18", "3.10.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make env
          pip list
          . env/bin/activate; pip list; deactivate
      - name: Run non-integration tests
        if: github.event.inputs.run_only_non_integration_tests == 'true'
        run: |
          make run_non_integration_tests
      - name: Run non-integration and integration tests
        if: github.event_name == 'push' || github.event.inputs.run_only_non_integration_tests == 'false'
        run: |
          make run_non_integration_tests
          make run_integration_tests
